### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kurtmaile** [databricks/databricks-cli#1]
Hi!

Awesome new repo very exciting- the CLI will be super useful for CI/CD and automation!  Awesome - cant wait for full API support.

Is there are roadmap for API coverage?

As a side note, in the absence of the *full* CLI, does databricks offer some accelerator shell scripts for interacting with their various APIs?

Cheers

**Comment by andrewmchen** [comment]
We're looking forward to adding the Workspace API soon! 

https://github.com/databricks/databricks-cli/issues/5

**Comment by andrewmchen** [comment]
We're adding the Clusters and Jobs APIs soon for release `0.4`. Also we just released a blog post about CI/CD which includes a script using this CLI. https://databricks.com/blog/2017/10/30/continuous-integration-continuous-delivery-databricks.html

**Comment by kurtmaile** [comment]
Awesome work Andrew the CLI is great congrats on this release.....cant wait for the rest of the APIs to be ported across as well is its complete parity with native API.  Being able to completely use just the CLI for automation would be super cool....once again congrats!

**Comment by nfx** [comment]
Please upgrade to the latest version. It seems that the version you're referring is too old.
