### ISSUE TITLE
Error: AttributeError: 'module' object has no attribute 'PROTOCOL_TLSv1_2'

### ISSUE THREAD

**Issue by vedantja** [databricks/databricks-cli#101]
installed databricks-cli with pip3. Double checked I have latest version of open-ssl and upgraded python. Still getting the same message.

**Comment by mengxr** [comment]
See https://github.com/databricks/databricks-cli/blob/master/README.rst#known-issues.

**Comment by vedantja** [comment]
I need to follow these steps:
1. Install OpenSSL for python version. In this python2.7.9:
pip install --upgrade pyopenssl
2. Reinstall/upgrade Databricks CLI 
pip install --upgrade databricks-cli

**Comment by Dhiyanu290100** [comment]
@vedantja it havent worked bro...
