### ISSUE TITLE
Passwords with %

### ISSUE THREAD

**Issue by dougbateman** [databricks/databricks-cli#103]
The Databricks CLI fails with a string interpolation error if the password contains a %.

doug:~$ databricks workspace list /Users
Error: InterpolationSyntaxError: '%' must be followed by '%' or '(', found: v'%pXXXXXXXXXXX'

**Comment by dougbateman** [comment]
The quick workaround was to edit my .databrickscfg and change % to %%.

**Comment by andrewmchen** [comment]
Thanks for reporting! Looks like we need to use raw mode when parsing the config. https://docs.python.org/2/library/configparser.html#ConfigParser.ConfigParser.get

**Comment by nfx** [comment]
Please upgrade to the latest version. It seems that the version you're referring is too old.
