### ISSUE TITLE
Error when running on Python 3.6

### ISSUE THREAD

**Issue by Arvinds-ds** [databricks/databricks-cli#106]
I tried `pip install databricks-cli` (v 0.6.0) on Python 3.6.4 and when I try any command (say `databricks clusters list`). I get the following error
`Error: TypeError: a bytes-like object is required, not 'str'`

Does the cli support Python 3.6?

**Comment by andrewmchen** [comment]
Could it be due to this issue? https://github.com/databricks/databricks-cli/issues/100

I'll put out a fix for that issue shortly. For the time being, using token auth or python 2 should work.
