### ISSUE TITLE
get_api_client used as library

### ISSUE THREAD

**Issue by abizeradenwala** [databricks/databricks-cli#129]
It would be good if there was an option to be able to pass the host, username, password/token to get_api_client call and if they are not passed then read it from the config . Currently get_api_client just directly reads from the config on disk.

**Comment by shea-parkes** [comment]
It looks like they made an `sdk` subpackage that makes it friendly to import bits-and-bobs.  You can find the subpackage under `databricks_cli/sdk`.  There is a `api_client.py` module there that has a nice `ApiClient` class that sure looks like its meant for library usage.

**Comment by nfx** [comment]
Please upgrade to the latest version. It seems that the version you're referring is too old.
