### ISSUE TITLE
Add way to configure databricks-cli without going through prompt.

### ISSUE THREAD

**Issue by andrewmchen** [databricks/databricks-cli#14]

**Comment by alonisser** [comment]
This is supported in the 3.7.dev0 version - configuring by environment variables

**Comment by bgrnwd** [comment]
Would be nice if an example could be added to the documentation [here](https://docs.databricks.com/dev-tools/cli/index.html#set-up-authentication).

It's unclear to me if `databricks configure` still needs to be run after setting environment variables.
