### ISSUE TITLE
dbfs cp doesn't work

### ISSUE THREAD

**Issue by kazemSafari** [databricks/databricks-cli#142]
I have a windows os and i am trying to import a file from my local machine into databricks.
When i run the following code:
```
dbfs cp "train_dta.npy" dbfs:"/FileStore/train_data.npy"
```

I get this error
```
SyntaxError: invalid syntax
```

**Comment by kazemSafari** [comment]
I was wondering if anyone was ever able to do that, or if it is even possible to do that with python files in databricks.

**Comment by andrewmchen** [comment]
Can't seem to reproduce. You seem to have an extra `"` though in your command?

**Comment by kazemSafari** [comment]
Hi andrew! I tried it with another way and it worked! I manually uploaded my file to my databricks and then loaded it to file using ```np.load('dbfs/../train_data.npy```. But i am still wondering if it is possible doing the same using dbfs command.

**Comment by andrewmchen** [comment]
Yes it should definitely work with the `dbfs cp` command. Is it still not working?

**Comment by nfx** [comment]
Please upgrade to the latest version. It seems that the version you're referring is too old.
