### ISSUE TITLE
The cp command does not return an error code when the target resource already exists

### ISSUE THREAD

**Issue by edurdevic** [databricks/databricks-cli#15]
When copying a file to dbfs without `--overwrite` and the resource already exists on dbfs, no file is copied and no exception is raised.
This behaviour leads to expecting the cp was successful even when the cp action is not performed.

**Comment by andrewmchen** [comment]
To be clear this is only for recursive copy right? Would https://github.com/databricks/databricks-cli/issues/37 solve the issue?

**Comment by edurdevic** [comment]
Actually this problem is present even with non-recursive copy.
The following commands will not fail (will just output an error message), and the final content of 'dbfs:/test.txt' will be "v1".
`
echo "v1" > test.txt
dbfs cp test.txt dbfs:/
echo "v2" > test.txt
dbfs cp test.txt dbfs:/
echo $?
`
The command 'echo $?' will write 0, but it should be non zero.

**Comment by andrewmchen** [comment]
Gotcha, this PR should address it. https://github.com/databricks/databricks-cli/pull/49

**Comment by andrewmchen** [comment]
Should be addressed by https://github.com/databricks/databricks-cli/pull/49. Would appreciate if you tried QAing the change!

Build from master by doing
`pip install git+https://github.com/databricks/databricks-cli.git@master`
