### ISSUE TITLE
Check credentials on "configure"

### ISSUE THREAD

**Issue by eltermann** [databricks/databricks-cli#161]
While debugging the "JSONDecodeError" message (see #102), I figured out I miss-configured the credentials (host + token).

I now see what I did wrong and everything works fine.

However, the debugging would have been avoided if "databricks configure" command checked the credentials instead of silently exiting.

**Comment by krunalhd** [comment]
What was your issue? I am getting same error and not sure what I misconfigured

**Comment by eltermann** [comment]
@krunalhd, sorry by the delay.
I was trying to use the wrong token content (didn't read the "copy now or you'll lose it" and instead I copied the "token-ID" ¬¬)

**Comment by nfx** [comment]
Please upgrade to the latest version. It seems that the version you're referring is too old.
