### ISSUE TITLE
Missing option to permanently delete a cluster

### ISSUE THREAD

**Issue by david-noel** [databricks/databricks-cli#176]
There seems to be no option to use the cli to call this REST endpoint  

2.0/clusters/permanent-delete

https://docs.azuredatabricks.net/api/latest/clusters.html#permanent-delete

**Comment by david-noel** [comment]
Any chance to get this added?

**Comment by andrewmchen** [comment]
Yes, this is a missing feature from the CLI. I can take a look at patching this API this week.
