### ISSUE TITLE
Issue while installing databricks-cli

### ISSUE THREAD

**Issue by Anudeep91** [databricks/databricks-cli#189]
When I am trying to install the databricks cli through pip3. I am getting the following error messagre "Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None))
 after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection
.VerifiedHTTPSConnection object at 0x0000000001E107F0>: Failed to establish a ne
w connection: [WinError 10061] No connection could be made because the target ma
chine actively refused it')': /simple/databrics-cli/
  Could not find a version that satisfies the requirement databrics-cli (from ve
rsions: )
No matching distribution found for databrics-cli"
[databrickscliinstallerror.txt](https://github.com/databricks/databricks-cli/files/2553271/databrickscliinstallerror.txt)

Can anyone help me how to proceed with this...

**Comment by andrewmchen** [comment]
Looks kind of weird. Should `databrics-cli` be `databricks-cli`?

**Comment by SpaceRangerWes** [comment]
I fixed this by running 
```
git config --global --unset http.proxy 
git config --global --unset https.proxy
```
and restarting my terminal session.

**Comment by CyborgDroid** [comment]
> I fixed this by running
> 
> ```
> git config --global --unset http.proxy 
> git config --global --unset https.proxy
> ```
> and restarting my terminal session.

This fixed the issue for me as well. Thank you!

**Comment by nfx** [comment]
Please upgrade to the latest version. It seems that the version you're referring is too old.
