### ISSUE TITLE
Uninstall all libraries fails if cluster does not contain libraries

### ISSUE THREAD

**Issue by aaronkensci** [databricks/databricks-cli#191]
Databricks CLI uninstall all libraries fails if no libraries installed on cluster.
Sample cluster status:
**Command**: 
``` 
databricks libraries list --cluster-id <cluster_id> 
```
**Response**: 
``` 
{ 
    "cluster_id": "<cluster_id>" 
} 
```

Using the CLI command `uninstall` on a cluster which has no libraries installed returns an error.

**Command**: 
``` 
databricks libraries uninstall --all --cluster-id <cluster_id> 
```
**Response**: 
``` 
Error: b'{"error_code":"INTERNAL_ERROR","message":"Unexpected error"}' 
```

Ideally the CLI should succeed when uninstalling all libraries even if none are present.
At minimum it should return a descriptive message.

**Comment by andrewmchen** [comment]
Hm, this looks like a bug in our library API. Maybe @mclin can take a look when he get's back from vacation. Please ping this thread on Nov 26th if no response until then.

**Comment by aaronkensci** [comment]
Thanks for the quick follow up!

**Comment by aaronkensci** [comment]
@andrewmchen Ping!

**Comment by andrewmchen** [comment]
Thanks! I'll make a ticket for our internal bug tracker and update this thread with any updates.

**Comment by aaronkensci** [comment]
Thanks for the fix @andrewmchen! https://github.com/databricks/databricks-cli/pull/201
