### ISSUE TITLE
Getting an error trying to connect to an azure databricks instance using cli, Ubuntu 18.10

### ISSUE THREAD

**Issue by Mortuie** [databricks/databricks-cli#197]
Getting the error `invalid access token` however when I use the same token within the databricks-cli dockerfile I have no problems connecting to the cluster/service.

**Comment by amanpreet001** [comment]
Is there any solution to the 'invalid access token' issue?

**Comment by nfx** [comment]
Please upgrade to the latest version. It seems that the version you're referring is too old.
