### ISSUE TITLE
CLI does not work with python 3

### ISSUE THREAD

**Issue by sbourke** [databricks/databricks-cli#2]
I get the following error 

`Traceback (most recent call last):
  File "/usr/local/bin/dbfs", line 7, in <module>
    from databricks_cli.dbfs.cli import dbfs_group
  File "/usr/local/lib/python3.6/site-packages/databricks_cli/dbfs/cli.py", line 31, in <module>
    from databricks_cli.configure.cli import configure_cli
  File "/usr/local/lib/python3.6/site-packages/databricks_cli/configure/cli.py", line 29, in <module>
    from databricks_cli.configure.config import DatabricksConfig
  File "/usr/local/lib/python3.6/site-packages/databricks_cli/configure/config.py", line 24, in <module>
    import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'`

**Comment by andrewmchen** [comment]
Yes, unfortunately, one of our swagger generated dependencies does not support python3 -- for that reason we decided to only support python 2 at this time.

**Comment by cavanaug** [comment]
Just curious, what was the dependency that wasnt supported??

**Comment by sbourke** [comment]
I'm just going off of memory here as I've just setup python2 when using databricks CLI.

Mostly non backwards compatible changes with native python libs causing breaks.

**Comment by andrewmchen** [comment]
We autogenerate a pretty trivial SDK that wraps some of the APIs. That SDK and some other python2 -> 3 library renames breaks our compatibility. 

Is it a blocker to not have python3 support? If it is we can re-prioritize the engineering work to get it working with python3.

**Comment by cavanaug** [comment]
Its not a big deal for the cli since most linux distros have both.   I am far more interested in the official support for python 3 on the serverside for things like serverless and native support in the ui for creating python3 clusters.

**Comment by andreabedini** [comment]
The error @sbourke reported is because `ConfigParser` is in `configparser` module.

# Python 2 only:
from ConfigParser import ConfigParser

# Python 2 and 3 (after ``pip install configparser``):
from configparser import ConfigParser

**Comment by rkarimi** [comment]
Tried to fix import above and yet faced another error (there are yet more dependencies):

  File "//anaconda/bin/databricks", line 7, in <module>
    from databricks_cli.cli import cli
  File "//anaconda/lib/python3.6/site-packages/databricks_cli/cli.py", line 28, in <module>
    from databricks_cli.configure.cli import configure_cli
  File "//anaconda/lib/python3.6/site-packages/databricks_cli/configure/cli.py", line 29, in <module>
    from databricks_cli.configure.config import DatabricksConfig
  File "//anaconda/lib/python3.6/site-packages/databricks_cli/configure/config.py", line 35, in <module>
    from databricks_cli.sdk import ApiClient, DbfsService, WorkspaceService, JobsService, ClusterService
  File "//anaconda/lib/python3.6/site-packages/databricks_cli/sdk/__init__.py", line 54, in <module>
    from .service import *
  File "//anaconda/lib/python3.6/site-packages/databricks_cli/sdk/service.py", line 25, in <module>
    import StringIO
ModuleNotFoundError: No module named 'StringIO'

**Comment by rkarimi** [comment]
Indeed. Uninstalled past installation:
pip uninstall databricks-cli
Installed brew, installed python 2 and then run below and it worked:
pip2 install --upgrade databricks-cli

**Comment by louspringer** [comment]
If you are on linux or mac os, using pyenv, you can suppress the error with a small patch to the `databricks` shell script. You can leave a python 3 install as your global python version with something like `pyenv global 3.6.3`, depending on which python 3 version you've installed.  

1. `pyenv install` a python 2 version, e.g. `pyenv install 2.7.14`
1. `pyenv install` a python 3 version, e.g. `pyenv install 3.6.3`
1. `pyenv global` your python 2 version, e.g. `pyenv global 2.7.14`
1. `pip install databricks-cli`
1. Add an export to the `databricks` bash script at line 3 `export PYENV_VERSION=2.7.14`. You can locate the script for patching with `which databricks`
1. `pyenv global` back to your python 3 version, e.g. `pyenv global 3.6.3`

Something similar may work for Windows installations using `conda`.

**Comment by andrewmchen** [comment]
Should work on python3 in master.
