### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by LavMehta** [databricks/databricks-cli#214]
Error: ConnectionError: HTTPSConnectionPool(host='westeurope.azuredatabricks.net', port=443): Max retries exceeded with url: /api/2.0/secrets/scopes/list (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000016B68E4C160>: Failed to establish a new connection: [WinError 10060] 

1.Installed databricks CLI
2. Generated Token in Azure Databricks
3. databricks configure --token
4. Databricks Host : https://westeurope.azuredatabricks.net
5. Token:xxxxxxxxxxxxxxxxxxxxxxxxxx
6. databricks secrets create-scope --scope my-scope
Above mentioned Error

Also my question i am using Databricks in Azure not directly by logging into Databricks.com is that the reason of this error? because when for example i try : databricks workspace ls /Users/example@databricks.com , Instead of example i write my email address which is my user name and then should it stay databricks.com or should i change it to @westeurope.azuredatabricks.net. 

Thanks in Advance

**Comment by LavMehta** [comment]
It was a Proxy settings problem at local level , Problem solved so closing the issue.

**Comment by spsandy101** [comment]
I have a similar error:
Error: ConnectionError: HTTPSConnectionPool(host=')', port=443): Max retries exceeded with url: /api/2.0/jobs/list (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6f326f5b70>: Failed to establish a new connection: [Errno -2] Name or service not known',))
I don't have any proxies set up.
I log in with username and password (configured in ~/.databrickscfg), and do not use the token.

**Comment by LavMehta** [comment]
@spsandy101 Could you please ellaborate the steps you followed? Are you also trying to create Scope and secret?

**Comment by benjudechan123** [comment]
> It was a Proxy settings problem at local level , Problem solved so closing the issue.

How did you resolve this issue,  I am also having this issue

**Comment by prakashtc** [comment]
> > It was a Proxy settings problem at local level , Problem solved so closing the issue.
> 
> @LavMehta How did you resolve this issue, I am also having this issue

can you pls help me

**Comment by gijoe707** [comment]
> > It was a Proxy settings problem at local level , Problem solved so closing the issue.
> 
> @LavMehta How did you resolve this issue, I am also having this issue

have you checked if the configuration is correctly stored in the file ~/.databrickscfg
