### ISSUE TITLE
sending get arguments as parameters changes behaviour in python

### ISSUE THREAD

**Issue by matt-mercer** [databricks/databricks-cli#217]
w.r.t:  0.8.5
https://github.com/databricks/databricks-cli/pull/213/commits/817262a2ec664a7f4588a0b1a75b56d6ccee541d

in python, before the above change 
api = RunsApi(client)
result = api.list_runs(job_id, active_only=True)

would correctly filter active jobs ...
now sending a boolean argument for a get request gets encoded as  'True' or 'False' in the query string parameters meaning that the boolean parameters are not applied correctly ..

**Comment by nfx** [comment]
please upgrade to the latest version
