### ISSUE TITLE
conda support

### ISSUE THREAD

**Issue by jaroslawk** [databricks/databricks-cli#223]
Team,

I would like to place MLflow in conda forge. One of the dependencies of MLflow is ``` databricks-cli```

Will it be valuable to place it there?
I need a person who is willing to become a supporter.

Here is my attempt:
https://github.com/conda-forge/staged-recipes/pull/8101

**Comment by jaroslawk** [comment]
@andrewmchen can I add databricks-cli to conda-forge?
can I add you as the maintainer?

**Comment by andrewmchen** [comment]
The MLflow team was meaning to look into this actually! I'm a bit underwater these last couple of days but I'd like to take a look at this PR in the next couple of days...

**Comment by jaroslawk** [comment]
@andrewmchen I see no progress in this field from the MLflow team. 
Here is the issue I got for tracking it: 
https://github.com/mlflow/mlflow/issues/400

Do you know who should I contact to get any feedback?


About the databricks-cli:
I can take care of everything - all I need is approval to add you there as support.

Here is the PR:
https://github.com/conda-forge/staged-recipes/pull/8101#issuecomment-480251307

**Comment by yehoshuadimarsky** [comment]
Looks like this issue can be closed, it was accepted into conda-forge, that PR was closed.
https://github.com/conda-forge/databricks-cli-feedstock
