### ISSUE TITLE
Error: ValueError: Timeout value connect was Timeout(connect=None, read=None, total=None), but it must be an int, float or None.

### ISSUE THREAD

**Issue by sachinunravel** [databricks/databricks-cli#231]
Getting error while running any of the Databricks CLI command. Following is the error statement:

> Error: ValueError: Timeout value connect was Timeout(connect=None, read=None, total=None), but it must be an int, float or None.

Python urllib3 version : urllib3==1.25.3
python requests version: requests==2.22.0

Is there anything I am missing?

**Comment by sachinunravel** [comment]
Databricks CLI version : databricks-cli==0.8.6

Same issue was raised on the forum here : https://forums.databricks.com/questions/18918/databricksdbfs-cli-cron-job-problem.html

**Comment by nfx** [comment]
Please upgrade to the latest version
