### ISSUE TITLE
Running Python code in Databricks through DataFactory -Error: Could not find a version that satisfies the requirement pywin32==224 

### ISSUE THREAD

**Issue by srini99mkl** [databricks/databricks-cli#252]
Hello, I have uploaded .whl file to databricks through databricks CLI. I am seeing the following issue 

****Error: Could not find a version that satisfies the requirement pywin32==224**

**Description:** I have uploaded my python code-Whole folder including .whl file to Databricks through Databrick CLI.  I am trying to call my python through Datafactory I am getting the above error, i believe this related to Databricks any help would be greatly helpful!

Thanks.

**Comment by nfx** [comment]
@srini99mkl is this one still relevant?
