### ISSUE TITLE
Support passing of databricks token as an argument to CLI command.

### ISSUE THREAD

**Issue by SwadX** [databricks/databricks-cli#260]
The use case which we have in mind is , we want to run databricks cli from a CI server like jenkins and want to pass the databricks token from the credentials store to the jenkins pipeline stage at run time .

**Comment by andrewmchen** [comment]
Have you considered passing it through an environment variable? See https://docs.databricks.com/user-guide/dev-tools/databricks-cli.html#set-up-authentication

**Comment by SwadX** [comment]
@andrewmchen  , thank you. that should work for us.
