### ISSUE TITLE
Get Workspace

### ISSUE THREAD

**Issue by m1nkeh** [databricks/databricks-cli#288]
Is there any way to list the name of the workspace that i am connected to with the databricks-cli ?

I have a bunch of workspaces, all in the same region, and always struggle to figure out which api key is for which  🙄

Right now, i sort of have to guess with cluster names..

Ta.

**Comment by m1nkeh** [comment]
Guess not 😕

**Comment by nfx** [comment]
there's no api for this at the moment 🤷
