### ISSUE TITLE
Python 2.7 no module named configparser

### ISSUE THREAD

**Issue by Smurphy000** [databricks/databricks-cli#293]
As far as I know, python 2 uses ConfigParser, so I am running into the error of no module configparser, which is python 3's name for it. Do I just need to move to 3 or is there another way to resolve this?

File "/usr/local/lib/python2.7/dist-packages/databricks_cli/configure/provider.py", line 25, in <module>
 from configparser import ConfigParser
 ImportError: No module named configparser

**Comment by nfx** [comment]
https://www.python.org/doc/sunset-python-2
