### ISSUE TITLE
CLI asks for username & password instead of token when using --profile

### ISSUE THREAD

**Issue by LoicH** [databricks/databricks-cli#302]
I successfully setup the default profile using "databricks configure", the prompt asked me for the host, then a token. I could see the content of my workspace with "databricks workspace ls", everything is working fine.

Now if I try to setup another profile (say, a production profile) using "databricks configure --profile prod", now after entering my host, the prompt asks for an username and password instead of a token.

I entered bogus information, then I changed the content of C:\Users\myself\.databrickscfg to correct my `prod` configuration and follow the `DEFAULT` one (with a different host and token), and now everything works fine.

How come the prompt did not ask for a token?

Plus the password is stored in plain text...

**Comment by andrewmchen** [comment]
You can provide the token with 
```
databricks configure --profile prod --token
```

**Comment by LoicH** [comment]
Thanks for your answer!

Is it normal though that the password is stored in plain text?
