### ISSUE TITLE
Pipeline deployment specifications

### ISSUE THREAD

**Issue by kfollesdal** [databricks/databricks-cli#305]
I have seen that databricks-cli have the command pipelines. With command deploy. But I have not succeeded to find any specifications for the deployment file, in documentation for delta or databricks. Can someone point me in the right direction?

Is there any command to list pipelines? I can see there is a command called get where you can give a pipeline-id. But how do I find the pipeline id?

**Comment by marmbrus** [comment]
The feature is still in private preview.  Stay tuned for more details!

**Comment by LucaSoato** [comment]
Hi, are there any updates about this?

**Comment by marmbrus** [comment]
We are now in public preview. You can sign up to join [here](https://databricks.com/product/delta-live-tables).

Here's the [user guide](https://docs.databricks.com/data-engineering/delta-live-tables/delta-live-tables-user-guide.html) and docs on [the json format for the pipeline settings](https://docs.databricks.com/data-engineering/delta-live-tables/delta-live-tables-configuration.html).
