### ISSUE TITLE
Typo in dbfs cli client ("youshould" should be "you should")

### ISSUE THREAD

**Issue by snosrap** [databricks/databricks-cli#322]
https://github.com/databricks/databricks-cli/blob/c20d5a99cae19414e28bfc8111f4ba2a1001d4c7/databricks_cli/dbfs/api.py#L239-L240

**Comment by andrewmchen** [comment]
Mind opening a PR against our repo? I'd be happy to merge this in for you.

**Comment by snosrap** [comment]
@andrewmchen sure thing. #324
