### ISSUE TITLE
dbfs cp of a large directory often results in "taking too long to process your request"

### ISSUE THREAD

**Issue by martinstuder** [databricks/databricks-cli#332]
When attempting to copy a somewhat larger directory with many files and subdirectories (~0.5GB) to dbfs using `dbfs cp --recusrive` we often experience the following error:
```
Error: b'{"message":"The service at this URL is taking too long to process your request. Please try again later or try a faster operation.","error_code":"TEMPORARILY_UNAVAILABLE"}\n'
```
Is there a way to configure a retry or should the client in general throttle operations in that case in order not to overload the endpoint?

**Comment by nfx** [comment]
@bogdanghita-db was this one fixed by retries?

**Comment by bogdanghita-db** [comment]
The only retries I added were for 429 (see [here](https://github.com/databricks/databricks-cli/pull/343/files)). I don't have context on this particular issue.

**Comment by nfx** [comment]
perfect, closing this issue!
