### ISSUE TITLE
Cannot Create Databricks-Backed Secret Scope using Secrets CLI

### ISSUE THREAD

**Issue by osuleiman** [databricks/databricks-cli#334]
The new Secrets CLI introduced the ability to create AKV secret scope and added new parameters to specify the resource ID of the AKV resource and its DNS name. The problem is that for Databricks-backed scope, it will still ask you to provide those parameters even though they are not needed as per the screenshot below:

![image](https://user-images.githubusercontent.com/34806809/95473553-e6f7c100-098c-11eb-87b5-1d6f27ac0d23.png)

To workaround this, you need to add the AKV parameters with dummy values and it will work as expected or downgrade to 0.12.0.

**Comment by pieterlaurens** [comment]
Workaround of adding dummy parameters works for me. Thanks a lot.

**Comment by JCZuurmond** [comment]
It is solved by this commit: https://github.com/databricks/databricks-cli/commit/929ac6ec423dfa7885ec07ce5fb12ea124ebace1

Waiting for a new release now.

**Comment by osuleiman** [comment]
This is fixed in databricks-cli==0.12.2 released yesterday.
