### ISSUE TITLE
databricks workspace import_dir fails since 0.12.1

### ISSUE THREAD

**Issue by rom1gal** [databricks/databricks-cli#337]
Hi all,

Since version 0.12.1 (the same code works correctly when using version 0.12.0) we are not able to issue the following command (running from an Azure DevOps agent running Ubuntu 18.06) : 

`databricks workspace import_dir /home/vsts/work/r1/a/Notebooks /ASI.Test/20201012072959-release-47
`

The following error is triggered : 

```
Traceback (most recent call last):
  File "/usr/local/bin/databricks", line 5, in <module>
    from databricks_cli.cli import cli
  File "/usr/local/lib/python3.6/dist-packages/databricks_cli/cli.py", line 37, in <module>
    from databricks_cli.secrets.cli import secrets_group
  File "/usr/local/lib/python3.6/dist-packages/databricks_cli/secrets/cli.py", line 54, in <module>
    type=click.Choice(['AZURE_KEYVAULT', 'DATABRICKS'], case_sensitive=True),
TypeError: __init__() got an unexpected keyword argument 'case_sensitive'
```

Thanks in advance

**Comment by rom1gal** [comment]
Hi,

Any news about that issue ?

Regards

**Comment by nfx** [comment]
It seems that the version you're referring is too old.
