### ISSUE TITLE
Idempotent `databricks secrets create-scope`

### ISSUE THREAD

**Issue by JCZuurmond** [databricks/databricks-cli#340]
Hi,

If we create a secret scope using the cli, the operation is not `idempotent`.

```
$ databricks secrets create-scope --scope my_scope --scope-backend-type AZURE_KEYVAULT --resource-id <resource id> --dns-name <dns name> --initial-manage-principal users
$ databricks secrets create-scope --scope my_scope --scope-backend-type AZURE_KEYVAULT --resource-id <resource id> --dns-name <dns name> --initial-manage-principal users
Error: b'{"error_code":"RESOURCE_ALREADY_EXISTS","message":"Scope my_scope already exists!"}'
```
We get a different outcome when running the same command twice. In the later case I would prefer no error, but that the exiting secret scope is updated, i.e. that  if the `backend type`, `resource id`, `dns name` or `initial manage principal` is different this updated accordingly.

**Comment by nfx** [comment]
update: this is purely backend issue and cannot be addressed on CLI
