### ISSUE TITLE
Changing on filenames in importing

### ISSUE THREAD

**Issue by brenolacerda** [databricks/databricks-cli#36]
When I import my workspace from databricks, somes files have its name altered. Usually the last letter is missing.

**Comment by andrewmchen** [comment]
Could you leave some more information? Are you moving files from Databricks to the local filesystem? The other way? What filenames are being altered?

**Comment by brenolacerda** [comment]
So, I send some files with this command "databricks workspace import_dir -o PathOrigin /Users/myUserName/Projects/". But, I have a file called 'my_battery', when I import to databricks, this file have its name altered for 'my_batter'.

**Comment by andrewmchen** [comment]
Is the file name exactly `my_battery`?

**Comment by brenolacerda** [comment]
file names altered: run_ah_battery, ah_battery, ah_history

Seems to me databricks-cli deletes the last letter when this letter is 'y'.

**Comment by brenolacerda** [comment]
We found the error.

If file name have last letters 'py' in python files, the last letters are deleted. (e.g. samplepy.py ~ sample.py)

The same error happens in sql files, and scala files.

**Comment by andrewmchen** [comment]
I can reproduce the problem. Thanks for reporting it!

**Comment by andrewmchen** [comment]
`'apy.py'.rstrip('.py') == 'a'` and not `apy`..

**Comment by andrewmchen** [comment]
Closed by #46
