### ISSUE TITLE
GET /repos returning ENDPOINT_NOT_FOUND

### ISSUE THREAD

**Issue by soonmyeongyoon** [databricks/databricks-cli#383]
Currently testing some repo operations using API, but looks like the root endpoint GET /repos is not working as expected.

Env:
- Python v3.6.9
- Authenticating through Databricks PAT
- Workspace on Azure
- CLI version 0.15.0

Repro:
- WHEN databricks repos list is run
- Error message received Error: b'{"error_code":"ENDPOINT_NOT_FOUND","message":"No API found for \'GET /repos\'"}'

Confirm that other repo endpoints like databricks repos get [--path] works correctly.

**Comment by nfx** [comment]
repos are out of private preview, so this should be resolved now.
