### ISSUE TITLE
[BUG] creating a repo without notebooks succeeds but the command status is failed

### ISSUE THREAD

**Issue by renardeinside** [databricks/databricks-cli#388]
to reproduce - create trying a Repo from empty GitHub repo :
```
databricks repos create --url <some-url>--provider github
```
Command status will be failed with error:
```
Error: b'{"error_code":"RESOURCE_DOES_NOT_EXIST","message":"NOTE: Databricks Repos will only clone Databricks notebooks from the remote repo. This repo does not contain any Databricks notebooks."}'
```
However, the repository will be created.

**Comment by nfx** [comment]
@jengler can you look at this one as well?

**Comment by nfx** [comment]
Please upgrade to the latest version. It seems that the version you're referring is too old.
