### ISSUE TITLE
PERMISSION_DENIED error when issuing the repos UPDATE command

### ISSUE THREAD

**Issue by heiqs** [databricks/databricks-cli#404]
I am trying to update the branch of a repo in databricks using cli. However, when I issue the following command

`databricks repos update --path /Repos/test/test --branch dev
`

I get the following error even with setting the token:

`Error: b'{"error_code":"PERMISSION_DENIED","message":"Azure Active Directory credentials missing. Ensure you are either logged in with your Azure Active Directory account or have setup an Azure DevOps personal access token (PAT) in User Settings > Git Integration. If you are not using a PAT and are using Azure DevOps with the Repos API, you must use an AAD access token. See https://docs.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/aad/app-aad-token for steps to acquire an AAD access token."}'`

Other commands like listing repos work as expected.

The CLI version is 0.16.2.

**Comment by djm2k** [comment]
Issue is still present in 0.16.6.

**Comment by nfx** [comment]
@jengler it doesn't seem to be a CLI issue

**Comment by nfx** [comment]
error clearly states that you have to configure a PAT token. this is not a CLI issue

**Comment by bjtho08** [comment]
I don't think this should be closed. I was facing the same issue. The message clearly states that if I use azure AD, then I need to use an AAD token, but depending on what I am trying to achieve with the cli (or the underlying api) I need to specify either an AAD access token or an AAD management token along with an AAD access token. Currently, the cli does not support management tokens along with access tokens. I would argue that this represents a bug in the code.

I faced this issue when trying to create a azure devops build pipeline to automatically update a repo on databricks when a new commit was created on a specific branch.
In the devops release pipeline, the issue is not present, even though it is the same api call.

**Comment by djm2k** [comment]
> I faced this issue when trying to create a azure devops build pipeline to automatically update a repo on databricks when a new commit was created on a specific branch. In the devops release pipeline, the issue is not present, even though it is the same api call.

I found myself in the exact same scenario. It's not obvious that you actually need to change the Git Provider type like so:
1. Browse to Settings > User Settings > Git Integration
2. Click **Change settings** 
3. Select **Azure DevOps Services (personal access token)**
4. Generate a PAT in Azure DevOps and copy it in.

After which I was able to update repos using just databricks host and token ENV variables in the pipeline.

**Comment by bjtho08** [comment]
> > I faced this issue when trying to create a azure devops build pipeline to automatically update a repo on databricks when a new commit was created on a specific branch. In the devops release pipeline, the issue is not present, even though it is the same api call.
> 
> I found myself in the exact same scenario. It's not obvious that you actually need to change the Git Provider type like so:
> 1. Browse to Settings > User Settings > Git Integration
> 2. Click **Change settings** 
> 3. Select **Azure DevOps Services (personal access token)**
> 4. Generate a PAT in Azure DevOps and copy it in.
> 
> After which I was able to update repos using just databricks host and token ENV variables in the pipeline.
> 
While that would solve the issue, the fact is that the error message clearly states that if one is using devops services (active directory), then the cli needs to authenticate with an AAD token. Nowhere does it explain that this only works for certain cli commands and specific conditions. I think that certainly both the cli documentation and Microsoft's databricks docs should reflect these limitations if the databricks team is not inclined to label it as a bug.

**Comment by alexott** [comment]
@bjtho08 to perform update of the Repos (and to create checkout) you need to have 2 tokens:

1. PAT or AAD token to authenticate against Databricks REST API
2. Git provider token to authenticate from Databricks Control Plane to the Git provider.  This Git provider token could be set either via UI or use [Git Credentials REST API](https://docs.databricks.com/dev-tools/api/latest/gitcredentials.html).

**Comment by bjtho08** [comment]
> @bjtho08 to perform update of the Repos (and to create checkout) you need to have 2 tokens:
> 
> 1. PAT or AAD token to authenticate against Databricks REST API
> 2. Git provider token to authenticate from Databricks Control Plane to the Git provider.  This Git provider token could be set either via UI or use [Git Credentials REST API](https://docs.databricks.com/dev-tools/api/latest/gitcredentials.html).

I have not been able to use neither the repos API nor Git Credentials API without supplying both an AAD Bearer token and an AAD Management token (with the `X-Databricks-Azure-SP-Management-Token` header). I gave spent countless hours reading through the Microsoft Azure docs and using your nutter repos demo, but nothing worked without the additional management token.

**Comment by alexott** [comment]
This is really described in rest api docs for case when service principal isn’t a part of the workspace yet: https://docs.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/aad/service-prin-aad-token#--api-access-for-service-principals-that-are-not-workspace-users

**Comment by bjtho08** [comment]
> This is really described in rest api docs for case when service principal isn’t a part of the workspace yet: https://docs.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/aad/service-prin-aad-token#--api-access-for-service-principals-that-are-not-workspace-users

I would say this supports my claim that the two tokens you mentioned earlier are not enough unless you have a premium plan workspace (a requirement for using SCIM or the ui equivalent) and therefore the databricks-cli does not work as expected.
