### ISSUE TITLE
Documentation of runs cli does not match implementation

### ISSUE THREAD

**Issue by epilif1017a** [databricks/databricks-cli#415]
Although the databricks documentation references we can append `--version=2.1` to `databricks runs` commands, the same throws an error when we put that option in. Moreover, by looking at the code, `--version` does not appear to be one of the click.options, so the actual implementation does not seem to match the documentation here: https://docs.databricks.com/dev-tools/cli/runs-cli.html 

Suggested change would be to put that as a click option and pass it downstream to the api calls.

**Comment by epilif1017a** [comment]
Hi team, 

Any news on the issue?

Best regards,
Carlos

**Comment by nordp** [comment]
Hi @epilif1017a,

Thanks for reporting this, please take a look at #434 and let me know if this PR would solve your issue.

**Comment by epilif1017a** [comment]
Hi @nordp ,

LGTM. Really appreciated! I'll be waiting for the next release then. Thanks a lot!
