### ISSUE TITLE
databricks-cli cannot be installed with new setuptools version v60.9.0

### ISSUE THREAD

**Issue by BurakYilmaz92** [databricks/databricks-cli#432]
Not sure you guys need a fix or is it something in setuptools side. But there is also an issue over there 
https://github.com/pypa/setuptools/issues/3104

In short, 
after `pip install databricks-cli` command, it cannot find the dbfs or databricks command

**Comment by pietern** [comment]
Per the discussion in the issue you linked, this was fixed in https://github.com/pypa/setuptools/pull/3106 and released in v60.9.1.

Thanks for reporting the issue.
