### ISSUE TITLE
NotADirectoryError when running workspace export_dir on Windows

### ISSUE THREAD

**Issue by snosrap** [databricks/databricks-cli#438]
If I run `databricks workspace export_dir` on Windows, I get a `NotADirectoryError` error when attempting to download directories with invalid Windows names (e.g., all the databricks_automl subdirectories, all of which contain a colon).

Example:
```bash
> databricks workspace export_dir /Users/me@example.com .

*snip*

Error: NotADirectoryError: [WinError 267] The directory name is invalid: '.\\databricks_automl\\22-01-05-17:00-automl_test_1-deadb33f'
```

Not only does it fail to download all the folders in /databricks_automl, it also bails out of the loop so none of the other files get downloaded.

**Comment by pietern** [comment]
This should have been fixed by #448.

Could you give the latest version of the CLI a try and see if it works for you?
