### ISSUE TITLE
ImportError: cannot import name 'PyJWTError' 

### ISSUE THREAD

**Issue by wobu** [databricks/databricks-cli#444]
in version 0.16.5 a new dependency to pyjwt>=1.5.0 has been introduced

unfortunatley the new implementation is incompatible with an pyjwt 1.5.x release due to

`from jwt import PyJWTError`

https://github.com/databricks/databricks-cli/blob/master/databricks_cli/oauth/oauth.py#L36

pyjwt introduced the type `PyJWTError` in the version 1.7.0

https://github.com/jpadilla/pyjwt/blob/1.7.0/jwt/exceptions.py
vs
https://github.com/jpadilla/pyjwt/blob/1.5.0/jwt/exceptions.py

**Comment by stormwindy** [comment]
Thanks for reporting @wobu. Bumped the minimum required version to 1.7.0. Made a new release at PyPI: https://pypi.org/project/databricks-cli/#history.

Please get on touch if you encounter any more problems. Closing the issue.
