### ISSUE TITLE
create_repo failing with AttributeError: 'str' object has no Attribute

### ISSUE THREAD

**Issue by neil90-db** [databricks/databricks-cli#479]
It seems the latest release 0.16.7 a validation was added for provider arguement https://github.com/databricks/databricks-cli/blob/master/databricks_cli/sdk/service.py#L1137-L1138, where in it will attempt to do provider.trim(), it should be provider.strip() as trim is not a function in python @alexott

**Comment by alexott** [comment]
#478 is already available

**Comment by pietern** [comment]
@alexott I created a separate PR to backfill tests. That it caused an issue without noticing means it lacked coverage.

**Comment by pietern** [comment]
We just released a patch version 0.16.8 that includes this fix.
