### ISSUE TITLE
About Py2.x support.

### ISSUE THREAD

**Issue by jsal13** [databricks/databricks-cli#502]
Howdy Databricks Peeps,

Given that Python 2.7 has been [sunset](https://kb.databricks.com/python/python-2-eol.html) last year and the CLI is marked as _experimental_ on the databricks page, is there any plan to cut over to supporting Py3.6+ and removing support for Py2.x?

(I know this is a fairly large lift, and especially irritating if consumers are using it in Py2.x, but I didn't see a roadmap and wanted to ask to make sure; there are certainly perks to supporting only one version, but perhaps not if there is a significant user-base still using the old version.)

Thanks!

**Comment by copdips** [comment]
curious to know the use cases that the data domain is still using py2.7
