### ISSUE TITLE
How to connect to a databricks cluster or a notebook from a IDE on a local machine.

### ISSUE THREAD

**Issue by shamanez** [databricks/databricks-cli#514]
I have configured the databricks-connect with Pycharm following the tutorial.   It worked perfectly when I want to  work with spark RDD, with a spark session. 

But I am using databricks notebooks to train deep learning models with spark data frames. I have realized there's no way to use other libraries installed in the databricks cluster. 

**For example, I can't use the torch library installed on the databricks cluster (I need to install it on my local machine).**  I want to develop and execute everything from the pycharm IDE, where the code gets executed in the databricks cluster (similar to [VS code remote dev](https://code.visualstudio.com/docs/remote/ssh) ). 

![image](https://user-images.githubusercontent.com/16892570/178100156-e7478ccf-2fdb-410f-847a-cc9612573264.png)

**Comment by pietern** [comment]
What you're describing needs the code to run on the driver, much like a notebook. There is no way to do this today with an external IDE. You'll have to use a Databricks notebook if you need all your code to directly execute on the cluster.

**Comment by nfx** [comment]
@shamanez you can get the list of libraries installed on Databricks Runtime by running a `pip freeze` command. Keep in mind, that from dbr to dbr library versions are different. At the moment it's one of the ways to solve your problem. 

Please also watch a remotely relevant DAIS talk - https://databricks.com/dataaisummit/session/power-sql-people-python-udfs-dbsql
