### ISSUE TITLE
“submit_run” call is not having a way to provide the "access-controls" as of now in databricks-cli:

### ISSUE THREAD

**Issue by shubhamnautiyal6894** [databricks/databricks-cli#519]
https://pypi.org/project/databricks-api/

I see that “submit_run” call is not having a way to provide the "access-controls" as of now, below are the only parameters supported:

db.jobs.submit_run(
run_name=None,
existing_cluster_id=None,
new_cluster=None,
libraries=None,
notebook_task=None,
spark_jar_task=None,
spark_python_task=None,
spark_submit_task=None,
timeout_seconds=None,
tasks=None,
headers=None,
version=None,
)

It will be better if we can support other parameters like "access-control" etc.

**Comment by pietern** [comment]
Thanks for reporting. This issue was also reported in #523 and we can track it there. Closing as duplicate.
