### ISSUE TITLE
databricks repos update --commit {COMMIT ID}

### ISSUE THREAD

**Issue by dsfrederic** [databricks/databricks-cli#533]
Feature request

Is it possible to make a command available that sets the head_commit_id without utilising a tag.

**Comment by pietern** [comment]
This is currently not possible per the [documentation for repos](https://docs.databricks.com/dev-tools/api/latest/repos.html#operation/update-repo). Either a branch or a tag is required.

Closing as we only track issues related to the CLI here, not product features. I'll pass it on to the team.
