### ISSUE TITLE
databricks configure - multiple deployments/hosts

### ISSUE THREAD

**Issue by kurtmaile** [databricks/databricks-cli#55]
Hi,

Is it possible to have multiple credential 'profiles' for different databricks deployments?  We have a dev, test and prod account (i.e 3 different hostnames) - each env is a seperate DBricks subscriptions.

Is it possible to have these seperate profiles configured  and used in a similar way to the aws cli --profile?

Thanks

**Comment by andrewmchen** [comment]
Hi @kurtmaile. Thanks for the request! It's something that has bothered me for a while now too :)

We've put it on the feature backlog and will prioritize the request accordingly.

**Comment by kurtmaile** [comment]
perfect! :)

**Comment by kurtmaile** [comment]
Hi hope you had a good break!

Any timelines for this?

**Comment by kurtmaile** [comment]
Hi Andrew,

Is this on the roadmap at all?  Very much needed feature, hope so!

Cheers
Kurt

**Comment by andrewmchen** [comment]
This is on the immediate roadmap. Half of the feature is here :) https://github.com/databricks/databricks-cli/pull/64

**Comment by kurtmaile** [comment]
Thanks!  Great feature closing this issue
