### ISSUE TITLE
Use databricks-cli in Python programmatically?

### ISSUE THREAD

**Issue by cozos** [databricks/databricks-cli#559]
Is it possible / recommended to use `databricks-cli` in Python? i.e.:

```py
from databricks_cli.dbfs import cli
cli.cp(...)
```

**Comment by mroy-seedbox** [comment]
We do use it to run things like `databricks workspace export_dir ...`.

You can run the cli commands directly by using either `%sh` at the top of a cell, or you can use something like `os.system()` in python.

**Comment by bsamseth** [comment]
I've used it programmatically to make [blackbricks](https://github.com/inspera/blackbricks). That works pretty well.

**Comment by pietern** [comment]
@cozos Good question. Please depend on the `.sdk` package and don't depend on the `.cli` sub-packages. For the former we know it won't break from release to release, whereas the `.cli` sub-packages are the direct implementation of the CLI itself and shouldn't be considered public API.

@bsamseth Nice, thanks for sharing!

**Comment by cozos** [comment]
Thanks for the help everyone.
