### ISSUE TITLE
import_dir swallows errors - blocking issue for cicd pipeline

### ISSUE THREAD

**Issue by azachar** [databricks/databricks-cli#569]
Hello, 
I have a pipeline that is using this command: 

```bash
databricks workspace import_dir ....
```
After some time our access token has expired, but the pipeline was still green. After a small investigation I found out, that there is a swallowing part of the error. Have a look here:

https://github.com/databricks/databricks-cli/blob/c62d8613b22cbc16f6314a6cdda956dfda84b383/databricks_cli/workspace/api.py#L147

Could that error be propagated instead?

Thank you!

Best regards,
Andrej

**Comment by pietern** [comment]
Thanks for reporting the issue. This doesn't look right. I was able to reproduce and posted a fix in #573.

**Comment by azachar** [comment]
Thanks!
