### ISSUE TITLE
databricks pipelines list maximum results 25

### ISSUE THREAD

**Issue by b-sellick** [databricks/databricks-cli#572]
My workspace has just reached 27 pipelines and I'm noticing that if I run "databricks pipelines list", I only see 25 results. I dont see params that can change that limit. Wondering what I can do about this. I am using the list function to pull down all pipelines, extract the ID's and names, in order to determine if a pipeline name exists or not which then drives using pipelines deploy and either adding an ID or not. With a pipeline not showing up in the list output, my code thinks it doesnt exist and is trying to "create" a pipeline that already exists

**Comment by b-sellick** [comment]
I was using 16.2. Have done an upgrade now to 17.3 and things are fine. Sorry, didnt pay attention to what version I was on. Thanks.

**Comment by pietern** [comment]
Thanks for the update and glad to hear this fixed your issue.
