### ISSUE TITLE
Repos CLI : add "force" option to the update command

### ISSUE THREAD

**Issue by Isarien** [databricks/databricks-cli#587]
In my use case I have a Azure devops pipeline that runs job cluster based on python file in a databricks repos.

Normally the repository is only modified by this pipeline (with the repos update command), but while testing I saw that the CLI returns an error when there has been a modification on a file in the databricks workspace

**Here is my suggestion :**

When trying to update a repository to a branch or to a tag, give the option to force the update even if changes have been made on the workspace.

**Comment by pietern** [comment]
It can be dangerous to forcibly update dirty repos as you lose any pending changes.

The API doesn't support this today, so the CLI can't either.

I have passed along your suggestion to the team.
