### ISSUE TITLE
Support more formats in import_dir

### ISSUE THREAD

**Issue by andrewmchen** [databricks/databricks-cli#59]
We should consider adding the format `JUPYTER` to `import-dir`. The tricky part about doing this is making sure that we have `export-dir` be able to handle `JUPYTER` notebooks in a symmetric way.

**Comment by granturing** [comment]
Why can't we just add the `.ipynb` extension to the `to_language` method?

https://github.com/databricks/databricks-cli/blob/master/databricks_cli/workspace/types.py#L36

For exporting, I think we should let the user decide whether to export Python notebooks as `.py` files or Jupyter format.
