### ISSUE TITLE
webhook_notifications not included in create_job method

### ISSUE THREAD

**Issue by Gaarv** [databricks/databricks-cli#601]
According to https://docs.databricks.com/dev-tools/api/latest/jobs.html#operation/JobsCreate, webhook_notifications can be included in the payload but seems missing in create_job API wrapper method, only email_notifications is present.

Should I open a PR for this ?

**Comment by MarkusFra** [comment]
I noticed this too, is there any update on this issue?

**Comment by pietern** [comment]
This has been fixed in #614.
