### ISSUE TITLE
update_job method does not update job's schedule

### ISSUE THREAD

**Issue by georgikoemdzhiev** [databricks/databricks-cli#616]
Hello, 

I am trying to change an existing job `schedule`. I am using the following python code that:

1. Get an existing job by name (i.e. using `filter` and `list` methods)
2. Change the job from step 1 to "Active"

There are no errors that are emitted after the `update_job` call. However, when I check the job in question on Databricks, it is still "Paused" 

```python
from databricks_cli.jobs.api import JobsApi
from databricks_cli.sdk.api_client import ApiClient
from databricks_cli.sdk.service import JobsService

api_client = ApiClient(host=databricks_host, token=databricks_token)
jobs = JobsApi(api_client)
jobs_service = JobsService(api_client)

job_list = jobs.list_jobs()["jobs"]

job_name = "DP DataSync Job"
result_list = list(
    filter(
    lambda job: job['settings']['name'] == job_name, job_list)
    )

job = result_list[0]
job_id = job["job_id"]
job["settings"]["schedule"]["pause_status"] = "UNPAUSED"

print(f"Resetting job with id: {job_id}")

job_json = json.dumps(job, indent=4)

print(job_json)

jobs_service.update_job(job_id=job_id, new_settings=job)
```

And here is a screenshot from databricks UI:
![image](https://user-images.githubusercontent.com/11027608/225381839-d245a332-dd1e-4c4d-9721-e8b05eb58fbf.png)

**Note**: I am using version 17.4 of the databricks cli

**Comment by mroy-seedbox** [comment]
We've had the same issue when trying to update the job permissions via the API (not even modifying them, but adding more)... it seems like certain fields just don't get updated. 🤦‍♂️

Haven't tried it again in a long time though, so idk if it's been fixed. I'm surprised the `pause_status` has the same issue. 😐 

Have you tried by removing the `pause_status` key from the dict entirely?

**Comment by georgikoemdzhiev** [comment]
> We've had the same issue when trying to update the job permissions via the API (not even modifying them, but adding more)... it seems like certain fields just don't get updated. 🤦‍♂️

Oh wow, that is worrying to hear :/ 

> Have you tried by removing the `pause_status` key from the dict entirely?

Yes, just tried removing the key using:

```python
del job["settings"]["schedule"]["pause_status"]
```

but unfortunately, the status of the job is still "PAUSED", I am assuming that must be a default, I dunno.

Note: I would need to be able to change the job's status to both PAUSED and UNPAUSED

**Comment by pietern** [comment]
I suspect the issue here is that in this call:
```python
jobs_service.update_job(job_id=job_id, new_settings=job)
```

You need to pass `job["settings"]` instead of just `job`.

That said, using this CLI package as sort-of SDK is not great. Please give https://github.com/databricks/databricks-sdk-py a try instead. This proper SDK has type annotations for the full API surface, so problems like this are caught earlier.

**Comment by pietern** [comment]
There's no fix we can do for this in the CLI, so closing the issue.
