### ISSUE TITLE
databricks-cli - AttributeError: type object 'Retry' has no attribute 'DEFAULT_METHOD_WHITELIST'

### ISSUE THREAD

**Issue by isamrat28** [databricks/databricks-cli#634]
Recently, while executing `dbfs ls` after installing and setting up the **databricks-cli-0.17.6** in command line, I am getting the below error:

`Error: AttributeError: type object 'Retry' has no attribute 'DEFAULT_METHOD_WHITELIST'`

A while back, the databricks-cli was working as expected and this seems to be an issue with the upgraded versions in one of the dependencies `urllib3-2.0.1` and/or `requests-2.30.0` but not sure though.

Could this be checked on a priority and a fix or work-around to this issue?

**Comment by yyonm** [comment]
Me too I'm geeting the same issue with databricks-cli-0.17.6 

`Error: AttributeError: type object 'Retry' has no attribute 'DEFAULT_METHOD_WHITELIST'`

It will be some fix for this issue? or maybe an a work-around?

Thanks. Regards.

**Comment by MilanaBorsuk** [comment]
Calling the following command: databricks secrets list-scopes
getting this error:
Error: AttributeError: type object 'Retry' has no attribute 'DEFAULT_METHOD_WHITELIST'

**Comment by jorgetorresvesta** [comment]
Same here. 
We were able to work around it by adding the following to requirements.txt in our python script, 
urllib3==1.26.15

**Comment by bstuddard** [comment]
Similar issue here. Any best guess when the fix will be released?

**Comment by BGerwe** [comment]
For what it's worth, I encountered the same issue with `databricks-cli-0.17.3`. It's the same underlying issue with `urllib3`, but wanted to clarify that rolling back the CLI version won't fix it.

**Comment by bigdatamoore** [comment]
I am having the same issue and this is breaking our deployment pipeline as we are using the databricks cli for that.

**Comment by bigdatamoore** [comment]
Workaround steps (activate your virtual env first if you have one)
```
pip uninstall urllib3
pip install urllib==1.26.15
```
That seemed to do the trick for me fwiw ....

**Comment by pietern** [comment]
Thanks for reporting the issue.

We just released version 0.17.7 to PyPI which includes a fix.
