### ISSUE TITLE
Error: AttributeError: type object 'Retry' has no attribute 'DEFAULT_METHOD_WHITELIST'

### ISSUE THREAD

**Issue by yashwantpawar** [databricks/databricks-cli#639]
We have following task which is failing with below error:
Tasks:
              #===== Configure Databricks CLI =====
              - task: configuredatabricks@0
                displayName: Configure Databricks CLI
                inputs:
                  url: $(databricks_url)
                  token: $(sm-dbw-access-token)
              #===== Deploy Notebooks to Workspace =====
              - task: deploynotebooks@0
                displayName: Deploy Notebooks to Workspace
                inputs:
                  notebooksFolderPath: $(Pipeline.Workspace)/drop/notebook
                  workspaceFolder: /NOTEBOOKS/etl1
error:
Starting: Deploy Notebooks to Workspace
==============================================================================
Task         : Deploy Databricks Notebooks
Description  : Recursively deploys Notebooks from given folder to a Databricks Workspace
Version      : 0.5.6
Author       : Microsoft DevLabs
Help         : 
==============================================================================
/opt/hostedtoolcache/Python/3.10.6/x64/bin/python -V
Python 3.10.6
Version: 3.10.6

Python3 selected. Running...
/opt/hostedtoolcache/Python/3.10.6/x64/bin/databricks workspace import_dir -o --profile AZDO /home/vsts/work/1/drop/notebook /NOTEBOOKS/etl1
Error: AttributeError: type object 'Retry' has no attribute 'DEFAULT_METHOD_WHITELIST'

##[error]The Notebooks import process failed.
Finishing: Deploy Notebooks to Workspace

We also think issue could also be caused by 
https://github.com/urllib3/urllib3/pull/2086/commits/ba593472e6b7230038f73560dde5321e72471246

We are using the task that uses databricks cli, when do you expect a permanent fix as this is affecting all our pipelines?

**Comment by edobrynin-dodo** [comment]
It's a known problem, was already reported and the PR with fix was already created. 
You can check Issues list to find a temp workaround, could resolve your problem before the fix will be released

**Comment by pietern** [comment]
We just released version 0.17.7 to PyPI which includes a fix.

**Comment by yashwantpawar** [comment]
@pietern, @edobrynin-dodo - Does this mean going forward, we don't need to add temporary fix given in below link to run  'Deploy Databricks Notebooks' yaml task ?
https://github.com/databricks/databricks-cli/issues/634

**Comment by pietern** [comment]
@yashwantpawar That is correct. Just make sure you install version 0.17.7.

**Comment by yashwantpawar** [comment]
@pietern - when you say install version 0.17.7, which version you are talking about? How can we get this installed using yaml task?

Thank you.

**Comment by pietern** [comment]
@yashwantpawar It looks like you're using Azure DevOps. If the step you're using uses the latest version of databricks-cli by default it should work out of the box. Otherwise you might need to specify this version in a configuration somewhere.
