### ISSUE TITLE
Is the urllib3<2 pin necessary?

### ISSUE THREAD

**Issue by jtilly** [databricks/databricks-cli#644]
Currently, `urllib3` is pinned: https://github.com/databricks/databricks-cli/blob/dd47ce4b42cd3ad17fc74022651aa0dbbbaf1d98/setup.py#L45 

This happened in https://github.com/databricks/databricks-cli/pull/637. Is this pin (still) necessary?

The PR description makes it sound like we needed this pin for `requests`. But `requests` should be fine with `urllib3<3`, see [here](https://github.com/psf/requests/blob/6e5b15d542a4e85945fd72066bb6cecbc3a82191/setup.py#L64).

This caused some hiccups on the conda packaging side (where the pin was missing), see https://github.com/conda-forge/databricks-cli-feedstock/pull/23.

**Comment by shreyas-goenka** [comment]
@jtilly You are right, the upper bound can be increased to 3 here. I have created an issue for tracking this in our backlog. Please let us know if this is blocking and we can prioritize cutting a PR for this.

https://github.com/databricks/databricks-cli/issues/645

**Comment by mrmasterplan** [comment]
+1 this breaks my pipeline. I would appreciate a fix.
