### ISSUE TITLE
add sql_params to JobsApi.run_now

### ISSUE THREAD

**Issue by danielhaviv** [databricks/databricks-cli#653]
SQL tasks that accept parameters require the `sql_params` parameter in the request which currently the cli does not support.

**Comment by danielhaviv** [comment]
Thanks, that should do it.
Should I leave the issue open (to add support for sql_params in the cli)?

**Comment by pietern** [comment]
No need. For the CLI we're focusing on https://github.com/databricks/cli where this parameter can already be specified.
