### ISSUE TITLE
[Question] A question about the future of this Databricks CLI

### ISSUE THREAD

**Issue by allebacco** [databricks/databricks-cli#657]
I am using the Python Databricks CLI since two years and It simplifies the way I am interacting with REST APIs.

However, in the last months you have created a Python SDK and a new (and more complete) CLI for the REST APIs.

So, my question is: what is the planned future of the Python Databricks CLI?

databrickslabs/dbx#806

**Comment by pietern** [comment]
Thanks for raising this issue. We're actively working on the new CLI, new SDKs, and more, and hadn't taken the time yet to add a notice to this repository. I have updated the README and added a pinned issue to address this.

If you have feedback or experience issues with either the new CLI or SDKs, please let us know!
