### ISSUE TITLE
databricks bundle command errors on downloading sig file,  443 no route to host

### ISSUE THREAD

**Issue by dyao1989** [databricks/databricks-cli#665]
Running: `Databricks CLI v0.201.0` on M1 Macbook 13.3.1 (Ventura). Terraform version is v1.5.5. 

When I use the following command to validate my asset bundle: 

```databricks bundle validate -e <enivornment name>```

I get this error:

```Error: error downloading Terraform: Get "https://releases.hashicorp.com/terraform/1.5.5/terraform_1.5.5_SHA256SUMS": dial tcp [2600:9000:250c:8800:5:e2b6:b380:93a1]:443: connect: no route to host```

I can curl that sig file no problem in my terminal, also updated my terraform version to no avail. I'm not on any VPN or proxy either. Other commands like `databricks bundle schema` work as well.

**Comment by dyao1989** [comment]
Ended up being an annoying DNS issue. This seems like a terraform issue anyways and not related to Databricks. Closing.

**Comment by pietern** [comment]
Thanks for both the report and the follow-up. Glad you got it to work.
