### ISSUE TITLE
SSLError when running any command

### ISSUE THREAD

**Issue by justinmills** [databricks/databricks-cli#93]
I just started having this problem a few days ago. I'm pretty sure I haven't installed any OSX updates that would have interfered. 

I tried re-installing my entire python/brew environment and it's the same. I'm able to hit API endpoints in the browser just fine so maybe there's something broken in the certificate chain in the python code?

Here's some sample output:

    Error: SSLError: HTTPSConnectionPool(host='<mycluster>.cloud.databricks.com', port=443): Max retries exceeded with url: /api/2.0/jobs/list (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

Using Python 2.7.13 and databricks-cli (0.5.0).

As suggested on some other python projects for similar errors I tried installing `requests[security]`, but it did not help.

**Comment by justinmills** [comment]
Sorry, turns out this was user error. I had been running a proxy in the background that I hadn't noticed. I was further confused by the fact that other python code was working just fine. Turns out I had either configured it to not use the system proxy or it didn't pick it up. 

The error message produced by the requests library is sparse and doesn't really give you any indication of what part of the certificate is wrong, so I assumed it was the original certificate without any proxy interference. Sorry about that!

**Comment by andrewmchen** [comment]
I've run into this exact issue while running MITMProxy before! The reason for the SSL validation error is explained here. https://github.com/mitmproxy/mitmproxy/issues/2547#issuecomment-325682712

**Comment by justinmills** [comment]
Thanks for the link..might have to check that out as a proxy alternative! 

I suppose one option would be for databricks-cli config to support a setting to set verify=False or explicitly bypass the system proxy. If I find I keep hitting this, I'll submit a PR.

**Comment by ChuliangXiao** [comment]
I have the same error 
conda 4.8.4
python 3.7.7
databricks-cli 0.11.0
Window 10

**Comment by matovitch** [comment]
I've manage to solve the same issue (within WSL/ubuntu) by adding the root CA certificate (you should be able to download it by looking at the TLS certificate chain with your web browser then look at the procedure specific to your OS to add these kind of certificates).

Then you need to determine the path to the CA bundle and set the environment variable REQUESTS_CA_BUNDLE with it. Cf. doc here:
https://requests.readthedocs.io/en/master/user/advanced/#ssl-cert-verification
